In [35]:
import pandas as pd
import json

In [36]:
df = pd.read_csv('Interruptions-experiment-table.csv')
df.head()

,[run number],number-of-doctors,number-of-patients,[step],count doctors,count patients,count interruptors with [(interrupt-status = true) and (type-int = 1)],count interruptors with [(interrupt-status = true) and (type-int = 2)],count interruptors with [(interrupt-status = true) and (type-int = 3)],count interruptors with [(interrupt-status = true) and (type-int = 0)],count doctors with [doc-interrupt-status = true],count doctors with [consequence-type = 1],count doctors with [consequence-type = 2],list-active-interruptors,type-active-interruptors,current-interrupt-doctors,conseq-interrupt-doctors
0,1,1,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0
1,1,1,2,1,1,0,0,0,0,1,1,1,0,[],[],[],[]
2,1,1,2,2,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
3,1,1,2,3,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
4,1,1,2,4,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]

In [37]:
cols = ['run_number', 
'number_of_doctors', 
'number_of_patients', 
'step', 
'count_doctors', 
'count_patients', 
'count_interrupters_alerts', 
'count_interrupters_devices', 
'count_interrupters_people', 
'count_interrupters_alarms', 
'count_doctors_interrupted', 
'count_doctors_consequence_resume_prev', 
'count_doctors_consequence_switch_task', 
'list_active_interrupters', 
'type_active_interrupters', 
'current_interrupt_doctors', 
'conseq_interrupt_doctors'
]

In [38]:
df.columns = cols
df.head()

,run_number,number_of_doctors,number_of_patients,step,count_doctors,count_patients,count_interrupters_alerts,count_interrupters_devices,count_interrupters_people,count_interrupters_alarms,count_doctors_interrupted,count_doctors_consequence_resume_prev,count_doctors_consequence_switch_task,list_active_interrupters,type_active_interrupters,current_interrupt_doctors,conseq_interrupt_doctors
0,1,1,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0
1,1,1,2,1,1,0,0,0,0,1,1,1,0,[],[],[],[]
2,1,1,2,2,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
3,1,1,2,3,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
4,1,1,2,4,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]

In [39]:
df[df.columns[1:]]

,number_of_doctors,number_of_patients,step,count_doctors,count_patients,count_interrupters_alerts,count_interrupters_devices,count_interrupters_people,count_interrupters_alarms,count_doctors_interrupted,count_doctors_consequence_resume_prev,count_doctors_consequence_switch_task,list_active_interrupters,type_active_interrupters,current_interrupt_doctors,conseq_interrupt_doctors
0,1,2,0,1,2,0,0,0,0,0,0,0,0,0,0,0
1,1,2,1,1,0,0,0,0,1,1,1,0,[],[],[],[]
2,1,2,2,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
3,1,2,3,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
4,1,2,4,1,0,0,0,0,1,1,1,0,[6],[0],[2],[1]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10663,5,10,189,5,19,0,1,1,0,2,5,0,[47 102],[3 2],[10 14],[1 1]
10664,5,10,190,5,19,0,1,1,0,2,5,0,[47 102],[3 2],[10 14],[1 1]
10665,5,10,191,5,19,0,1,1,0,2,5,0,[47 102],[3 2],[14 10],[1 1]
10666,5,10,192,5,19,0,1,1,0,2,5,0,[102 47],[3 2],[10 14],[1 1]
10667,5,10,193,5,19,0,1,1,1,3,5,0,[102 47],[3 2],[14 10],[1 1]

In [40]:
q = "number_of_doctors == 1 & number_of_patients == 2"
df_filtered = df.query(q)

In [41]:
df_filtered.shape

(601, 17)

In [42]:
data = []
for idx, row in df_filtered.iterrows():
    data_row = {}
    for col in df_filtered.columns[3:]:
        data_row[col] = row[col]
        data.append(data_row)
#print(data)

In [43]:
with open('interruptions.json', 'w') as fp:
    json.dump(data, fp)